name 'cmuench-n98magerun'
version '0.5.1'
source 'git://github.com/cmuench/puppet-n98magerun'
author 'Christian Münch'
license 'MIT'
summary 'n98-magerun Magento CLI Tool'
description 'n98-magerun Magento CLI Tool'
project_page 'http://github.com/cmuench/puppet-n98magerun'
dependency 'puppetlabs/stdlib', '>= 2.2.1'
dependency 'camptocamp/augeas', '>= 0.0.1'
